# Generated by Django 5.1.1 on 2024-10-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
