# Generated by Django 5.1.1 on 2024-10-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_categoria_nombre_solicitud_articulosolicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('revisada', 'Revisada'), ('en_ejecucion', 'En Ejecución'), ('finalizada', 'Finalizada'), ('rechazada', 'Rechazada')], default='nueva', max_length=20),
        ),
    ]
