# Generated by Django 5.1.1 on 2024-10-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='codigo',
            field=models.CharField(default='default_code', max_length=100, unique=True),
        ),
    ]
